# Generated by Django 4.2 on 2023-04-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_aggregation_function_alter_attribute_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='alias',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
