# Generated by Django 4.2 on 2023-04-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_aggregation_projection_projection_aggregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='aggregation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='app.aggregation'),
        ),
        migrations.AlterField(
            model_name='projection',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='app.attribute'),
        ),
    ]
