# Generated by Django 4.2 on 2023-04-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_aggregation_projection_projection_aggregation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='alias',
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='app.table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
