# Generated by Django 4.2 on 2023-04-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_projection_aggregation_and_more'),
        ('app', '0008_alter_attribute_name'),
    ]

    operations = [
    ]
