# Generated by Django 4.2 on 2023-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20230427_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='estimated_execution_time_not',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='not_join_order',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='pg_prefix',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
