# Generated by Django 4.2 on 2023-05-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_query_estimated_execution_time_not_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='pg_prefix',
            new_name='choosed_plan',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='estimated_execution_time',
            new_name='estimated_execution_time1',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='estimated_execution_time_not',
            new_name='estimated_execution_time2',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='join_order',
            new_name='join_order1',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='not_join_order',
            new_name='join_order2',
        ),
    ]
