# Generated by Django 4.2 on 2023-05-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_pg_prefix_query_choosed_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='prefix',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
