# Generated by Django 4.2 on 2023-05-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_execution_time_query_execution_time_hybride_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='join_order1',
        ),
        migrations.AddField(
            model_name='query',
            name='join_order',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
