# Generated by Django 4.2 on 2023-05-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_query_choosed_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='number_join',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='prefix_algo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='prefix_search_energy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='prefix_search_time',
            field=models.FloatField(null=True),
        ),
    ]
