# Generated by Django 4.2 on 2023-05-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_execution_energy_query_execution_energy_hybrid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='join_order',
            new_name='join_order_hinter',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='join_order2',
            new_name='join_order_pg',
        ),
        migrations.RemoveField(
            model_name='query',
            name='estimated_execution_time1',
        ),
        migrations.RemoveField(
            model_name='query',
            name='estimated_execution_time2',
        ),
    ]
