# Generated by Django 4.2 on 2023-05-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_join_order_query_join_order_hinter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='converge',
            field=models.FloatField(null=True),
        ),
    ]
