# Generated by Django 4.2 on 2023-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_query_json_plan_hinter_query_json_plan_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='json_plan_hinter_real',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='json_plan_pg_real',
            field=models.TextField(null=True),
        ),
    ]
