# Generated by Django 4.2 on 2023-05-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_query_json_plan_hinter_real_query_json_plan_pg_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='json_plan_hinter',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='json_plan_hinter_real',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='json_plan_pg',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='json_plan_pg_real',
            field=models.JSONField(null=True),
        ),
    ]
