# Generated by Django 4.2 on 2023-05-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_query_json_plan_hinter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='execution_energy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='execution_time',
            field=models.FloatField(null=True),
        ),
    ]
