# Generated by Django 4.2 on 2023-05-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_query_execution_energy_query_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='sf',
            field=models.FloatField(null=True),
        ),
    ]
