# Generated by Django 4.2 on 2023-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_selection_sf'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='attr',
            field=models.FloatField(null=True),
        ),
    ]
