# Generated by Django 4.2 on 2023-05-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_selection_attr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='attr',
            field=models.TextField(null=True),
        ),
    ]
